### ISSUE TITLE
Future of the repository

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixfmt#129]
As you might already know, we, the [RFC 101](https://github.com/NixOS/rfcs/pull/101) (Nix formatting) shepherd team, are intending to choose the nixfmt code base to implement the standard Nix formatting, including Nixpkgs (see #118). This decision is unlikely to change, even should the RFC pivot to a radically different output format — the nixfmt code base has proven to be very flexible in this regard.

The current plan of the RFC is to eventually put the chosen formatter repository into the [`NixOS` GitHub organization](https://github.com/nixos), and to continue maintaining it by a newly founded [Formatter team](https://github.com/happysalada/rfcs/blob/nix_formatting/0101-nix%20formatting.md#maintenance). The team is not fixed yet, but will probably consist of people already involved in the RFC, e.g. current and alumni shepherds. Of course you would be welcome in that team too, if you want.

The big question here is, would you agree to slowly transfer this repository to us for this goal? The alternative would be to fork nixfmt for the purpose of this RFC. To which extent that fork then would have to be "harder" or "softer", is not clear yet. But the main benefit of reusing the repository is the ability to keep the issue tracker intact.

In more detail, we propose the following actions:

- @piegamesde gets at least developer access to the repository for now. Giving full access to the team can be done later on when things are more final.
- (Optional.) A new release is made, since the last one was a year ago and quite a few things happened since (mostly bug fixes judging from the commit history).
- The new format WIP in #118 is merged into master.
- No new releases are made until the new format is final and stable. Bug fixes are backported to the latest release until then.
- Issues relating to the old format or that are otherwise fixed on master get closed.
- A new `nixfmt_unstable` attribute is added to Nixpkgs, allowing people to try out the RFC's format and give feedback in the issue tracker.
- Once the RFC gets accepted, the repository will be transferred to the NixOS organization, and the entire Formatter team will be granted access.
- The Formatter team takes care of the necessary steps towards migrating Nixpkgs, and any future maintenance.

Signed by:
- @piegamesde
- @infinisil
- @0x4A6F
- @tomberek

**Comment by Lucus16** [comment]
I'm okay with all of it but I'm not the owner. @gromakovsky ?

**Comment by gromakovsky** [comment]
@Lucus16 thanks for pingining me.

> @piegamesde gets at least developer access to the repository for now.

It shouldn't be a big deal, so I've just done that (provided `Write` access).

> (Optional.) A new release is made, since the last one was a year ago and quite a few things happened since (mostly bug fixes judging from the commit history).

Sounds good to me. What does it entail? Changing the version in `nixfmt.cabal`, updating the changelog, pushing a new tag, making a new release on GitHub and uploading this version to [Hackage](https://hackage.haskell.org/package/nixfmt). Anything else? I can make you a maintainer of the Hackage package if you want.

> The big question here is, would you agree to slowly transfer this repository to us for this goal? 

I personally don't mind, but let me discuss it internally first. I hope to get back to you soon.

> Of course you would be welcome in that team too, if you want.

Yep, I would like to have someone from existing employees of our company in that team, but that's another thing for me to discuss internally first. If we decide to do it, we will probably want to review #118 before it gets merged.

**Comment by gromakovsky** [comment]
> As you might already know, we, the https://github.com/NixOS/rfcs/pull/101 (Nix formatting) shepherd team, are intending to choose the nixfmt code base to implement the standard Nix formatting, including Nixpkgs (see https://github.com/serokell/nixfmt/pull/118). This decision is unlikely to change, even should the RFC pivot to a radically different output format — the nixfmt code base has proven to be very flexible in this regard.

Btw, I didn't read the whole discussion in https://github.com/NixOS/rfcs/pull/101 because it's too big, but in `0101-nix formatting.md` I see the following:

> From this evaluation, we decide that the code base of alejandra will be used as the base.

Do I understand correctly that you have changed your mind since then?

**Comment by infinisil** [comment]
@gromakovsky Indeed, we intend to close that RFC and open a new one once ready. We're working on the new RFC draft [here](https://github.com/nix-rfc-101/rfcs/blob/master/rfcs/0101-nix-formatting.md) for now, which is much more up-to-date

**Comment by infinisil** [comment]
> I personally don't mind, but let me discuss it internally first. I hope to get back to you soon.

Any updates on this?

**Comment by gromakovsky** [comment]
> The big question here is, would you agree to slowly transfer this repository to us for this goal?

Yes, we can transfer the repository, but please describe how you envision this process. AFAIU the plan is to eventually move it to https://github.com/nixos, but it's hard to predict when it will happen. Do you want it to be transferred to another organization as an intermediate step?

> Of course you would be welcome in that team too, if you want.

We'd like to have @Sereja313 in the team to be aware of what's going on, participate in discussions and coding. According to https://github.com/NixOS/rfcs/pull/101, I see that you have meetings from time to time. Is it possible to invite sergey.gulin@serokell.io and roman.melnikov@serokell.io to the next one?

**Comment by infinisil** [comment]
> Do you want it to be transferred to another organization as an intermediate step?

Oh that might be a good idea. In fact we just created https://github.com/nix-rfc-101/ as a temporary organization for the new RFC, but we could maybe discuss using it also as the temporary place for the nixfmt repository.

I sent Email invites to the bi-weekly meetings, next one is 2023-09-26 21:00 CEST. If the time doesn't work, let me know so we can find a better one. We also use [this Matrix room](https://matrix.to/#/#rfc-101:nixos.org) for asynchronous communication.

**Comment by infinisil** [comment]
For reference, the meeting notes for the discussion are [here](https://github.com/NixOS/rfcs/pull/101#issuecomment-1736293994), notably quoting:

> Wait for the RFC, then move to Nix organization

In anticipating of the RFC succeeding, I've also picked up some maintenance of nixfmt and did the nixfmt-0.6.0 release [two couple weeks ago](https://github.com/NixOS/rfcs/pull/101#issuecomment-1788097135) together with Sergey and @piegamesde.

**Comment by infinisil** [comment]
RFC has been merged, this can be cloned, see https://github.com/NixOS/nixfmt/issues/153 for further updates :)
