### ISSUE TITLE
Idea: Provide a diff mode

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixfmt#135]
Idea from @Lucus16, to allow using nixfmt to diff Nix files semantically. This then doesn't really require optimising for normal git line diffs if it was persistently used.

**Comment by infinisil** [comment]
E.g. changing
```nix
{
  inherit foo bar;
}
```

to

```nix
{
  inherit foo bar baz;
}
```

gives the diff

```diff
 {
   inherit
     foo
     bar
+    baz
   ;
 }
```

**Comment by dasJ** [comment]
Does this even have to be a nixfmt feature? This is achievable with a simple wrapper of `diff -u <(< default.nix) <(nixfmt < default.nix)`

**Comment by infinisil** [comment]
That works in some cases, but a truly semantic diff is trickier. I was recently pointed to https://github.com/Wilfred/difftastic though, which I believe does this already. And it's based on treesitter, so Nix is supported already!

I guess there's no reason this needs to be part of nixfmt in any case, so let's just close.
