### ISSUE TITLE
Consider making list formatting closer to attrsets

### ISSUE THREAD

**Issue by RuRo** [NixOS/nixfmt#136]
### Description

Currently, lists are formatted quite differently compared to attrsets. I think, that most of the arguments for why attrsets are formatted the way they are, apply equally well to lists. Therefore, lists should be formatted in a way similar to attrsets.

### Small example input

```nix
{
  attrset = { first = 1; second = 2; };

  list = [ "first = 1" "second = 2" ];

  longer_list_name = [ "this is" "a list that" "is barely longer" "than one line" ];
}
```

### Expected output

```nix
{
  attrset = {
    first = 1;
    second = 2;
  };

  list = [
    "first = 1"
    "second = 2"
  ];

  longer_list_name = [
    "this is"
    "a list that"
    "is barely longer"
    "than one line"
  ];
}
```

### Actual output

```nix
{
  attrset = {
    first = 1;
    second = 2;
  };

  list = [ "first = 1" "second = 2" ];

  longer_list_name =
    [ "this is" "a list that" "is barely longer" "than one line" ];
}
```

P.S. The ugly line break after `longer_list_name =` is actually a slightly more general problem that doesn't only affect lists, but also other elements that `nixfmt` doesn't "want"/know how to split. I'll be opening a separate issue for that problem shortly.

**Comment by piegamesde** [comment]
This should be fixed in #118
