### ISSUE TITLE
Discover Nix files

### ISSUE THREAD

**Issue by 9999years** [NixOS/nixfmt#152]
When run without any arguments and STDIN is a TTY, `nixfmt` should behave like `nixfmt .`, and discover all `.nix` files recursively.

**Comment by piegamesde** [comment]
We are currently a bit undecided where Nixfmt should have any of these features at all, see #151. But if we decide in favor, then this is something we'd likely want as well. I also agree that either way the current behavior is not a good UX

**Comment by infinisil** [comment]
In #151 we [decided](https://github.com/NixOS/nixfmt/issues/151#issuecomment-2008026386) to not further support this directory functionality in the future. We'll keep that issue open for now though.
