### ISSUE TITLE
Transfer to NixOS GitHub organisation

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixfmt#155]
As outlined in https://github.com/serokell/nixfmt/issues/153, this repository needs to be transferred to the [official NixOS organisation](https://github.com/nixos).

Action items:
- @Sereja313:
  - Please give repo admin access to @zimbatm, a NixOS org owner who can do the transfer
- @zimbatm:
  - Please add @Sereja313 to the NixOS organisation and add them to the [formatting team](https://github.com/orgs/NixOS/teams/nix-formatting/members)
  - Transfer this repository to https://github.com/NixOS/nixfmt
  - Give @infinisil and @piegamesde repository admin access who can then make further permission changes as necessary, including giving the formatter team write access

**Comment by Sereja313** [comment]
i sent an invitation to @zimbatm

**Comment by zimbatm** [comment]
done!
