### ISSUE TITLE
Retire web demo

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixfmt#157]
There's a web demo for nixfmt on https://nixfmt.serokell.io/

As this is becoming the new official Nix formatter (see #153), I don't think it is necessary to maintain that page anymore. Not having to do that also removes a bunch of overhead on the new official formatter team.

If Serokell still wants to maintain such a web demo, it would be best for that to happen in a Serokell-owned repo instead (since this one will be transferred to the NixOS organisation, see #155)

Otherwise my recommendation is to set up a redirect from the website to this repository (which GitHub will automatically redirect to the new repository once transferred).

Ping @Sereja313

**Comment by Sereja313** [comment]
We decided to keep the site for a few more months. So i'll move all the `nixfmt-webdemo` logic into a separate repo and then get rid of everything related to it in the `nixfmt` repo.

**Comment by infinisil** [comment]
Looks like CI isn't working anymore after the transfer due to the self-hosted runners, so I cleaned up CI in https://github.com/NixOS/nixfmt/pull/160

Shouldn't be a problem to remove it already since everything's in the git history

**Comment by infinisil** [comment]
Now implemented with https://github.com/NixOS/nixfmt/pull/162
