### ISSUE TITLE
Change licensing to remove individuals (companies?)

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixfmt#169]
Context: Currently, the license specifies that Serokell, @Lucus16, @piegamesde and me hold the copyright.

(from the team meeting today:)

- How do contributors get included in the copyright?
- CLA would address that question, don't recommend that though
- By contributing, people generally agree to have it be included under the same license/copyright
- [Nixpkgs has "and contributors"](https://github.com/NixOS/nixpkgs/blob/master/COPYING#L1)
- Preference: Removing individual copyright statements
  - Instead "nixfmt contributors"
  - Or "Serokell and nixfmt contributors"

This would be fine by me and @piegamesde, but what about you, @Lucus16?

And what does Serokell think about this, do we have to keep you listed explicitly in the copyright, or can we change it to just "nixfmt contributors"? Ping @Sereja313, @gromakovsky

In any case, we'll definitely update the `README.md` to be clear about `nixfmt` having been developed by Serokell originally.

**Comment by Lucus16** [comment]
> How do contributors get included in the copyright?

Contributers automatically retain the copyright to their work, regardless of any copyright notices. At least it works that way in most countries.

Note that copyright notices are a separate thing from a list of contributors which I believe has no legal meaning on its own. You are free to make a list of contributors and modify it as you see fit.

> CLA would address that question, don't recommend that though

I definitely wouldn't like a CLA, it would oppose the free flow of open source contributions.

> By contributing, people generally agree to have it be included under the same license ~/copyright~

I believe the Github terms of service ensure that contributions are made under the same license if the contributer owns the copyright to the code they submit. This does not apply to copyright, that does not get transferred.

Note that the terms of the license say copyright notices may not be altered or removed except to fix inaccuracies. In my case I don't mind you removing my copyright notices although I'm not sure that statement is enough to allow you to go against the license terms.

**Comment by gromakovsky** [comment]
I would prefer to retain `Serokell <hi@serokell.io>` in the copyright. If it gets refactored to be in only one place (rather than on per-file basis), I think it won't be a big deal. Listing major authors explicitly in the copyright sounds reasonable to me.
