### ISSUE TITLE
Reaching a stable list formatting requires formatting twice

### ISSUE THREAD

**Issue by TomaSajt** [NixOS/nixfmt#188]
### Description

Just a small thing I noticed while packaging stuff for Nixpkgs.

### Small example input

```
[ "hello"

]
```

### Expected output

```
[ "hello" ]
```

### Actual output
after first formatting
```
[
  "hello"
]
```
then after formatting again, it gives the correct
```
[ "hello" ]
```

**Comment by infinisil** [comment]
Looking into this, I'm thinking the following:

```nix
[ "string"

]
```

should be formatted like this:

```nix
[
  "string"

]
```

Because ["empty lines must be preserved"](https://github.com/NixOS/nixfmt/blob/3bcb63c13e7aaf0b8e14081cf0c14c44f62e840a/standard.md?plain=1#L68).

I've now implemented this in #201
