### ISSUE TITLE
Inconsistent list formatting

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nixfmt#190]
### Description

The following list formatting is quite inconsistent as I would expect both lists to be formatted very similar since they both use very similar syntax.

### Small example input

```nix
{
  nativeBuildInputs = [ protobuf ] ++ lib.optionals stdenv.isDarwin [ xcbuild.xcrun ];

  buildInputs = [
    zlib
    zstd
  ]
  ++ lib.optionals stdenv.isLinux [ xorg.libxcb ]
  ++ lib.optionals stdenv.isDarwin (with darwin.apple_sdk.frameworks; [
    SystemConfiguration
    VideoToolbox
  ]);
}
```

### Expected output

```nix
{
  nativeBuildInputs = [ protobuf ] ++ lib.optionals stdenv.isDarwin [ xcbuild.xcrun ];

  buildInputs = [
    zlib
    zstd
  ]
  ++ lib.optionals stdenv.isLinux [ xorg.libxcb ]
  ++ lib.optionals stdenv.isDarwin (
    with darwin.apple_sdk.frameworks;
    [
      SystemConfiguration
      VideoToolbox
    ]
  );
}
```

### Actual output

```nix
{
  nativeBuildInputs = [ protobuf ] ++ lib.optionals stdenv.isDarwin [ xcbuild.xcrun ];

  buildInputs =
    [
      zlib
      zstd
    ]
    ++ lib.optionals stdenv.isLinux [ xorg.libxcb ]
    ++ lib.optionals stdenv.isDarwin (
      with darwin.apple_sdk.frameworks;
      [
        SystemConfiguration
        VideoToolbox
      ]
    );
}
```

**Comment by piegamesde** [comment]
Which "both lists" do you mean here? I fail to see the inconsistency.

**Comment by SuperSandro2000** [comment]
I assigning two variables which are lists. They should be formatted with the same whitespace rules, not different ones.

**Comment by piegamesde** [comment]
(besides the point, but they are not lists but list concatenations)

Every expression has two possible formats. One expanded form and one compact form. This follows from the RFC: "Unless stated otherwise, any expression that fits onto one single line must be trivially formatted as such."

In addition to that, I still fail to see how the format you propose would be more consistent with the single-line format than the one Nixfmt currently does.

**Comment by SuperSandro2000** [comment]
If the assignment gets long enough to no longer fit one line, my proposed formatting requires less changes to get to the new formatting and generates a smaller and easier to grasp diff. Also when written out by hand it is more consistent, as it doesn't require an extra new line after the equal sign.

**Comment by infinisil** [comment]
We discussed this in the formatting team meeting today.

This format was accepted in the RFC, so we need to keep it as is. The reason why we decided against your proposed format is that it introduces [intermediate lines without extra indentation compared to the attribute set](https://github.com/NixOS/nixfmt/blob/87c4879b7a72a69726b76392847fb79a7044c6a6/standard.md#L1219), which makes [indentation not correspond as well to the code structure](https://github.com/NixOS/nixfmt/blob/87c4879b7a72a69726b76392847fb79a7044c6a6/standard.md#L110).

So let's stick to this formatting right now, but we can consider revisiting in a couple years when it's more established.

**Comment by SuperSandro2000** [comment]
I've just run into the same thing again https://github.com/NixOS/nixpkgs/commit/6d9cdbf4eec5fb2481824a85800b46bea2539d9d#diff-b19adb0eda71d89cec89ebcf357db024e96801055e160fbe8f624dc7e1bab0c0R74
https://github.com/NixOS/nixpkgs/commit/6d9cdbf4eec5fb2481824a85800b46bea2539d9d#diff-b19adb0eda71d89cec89ebcf357db024e96801055e160fbe8f624dc7e1bab0c0R120

I am not sure how you envision that a before two line change now suddenly can become a reformat of bigger chunks of the entire file. From a reviewer perspective this is really worrying and making things unnecessarily hard to review.
