### ISSUE TITLE
nixfmt adding not needed comma after arguments

### ISSUE THREAD

**Issue by Libadoxon** [NixOS/nixfmt#199]
### Description
nixfmt adds a not needed comma after the last argument in an expression parameter definition. Note this does not happen if the last argument is `...`

### Small example input

```nix
{ foo, bar, foobar }:
{
...
}
```

### Expected output

```nix
{
  foo,
  bar,
  foobar
}:
{
...
}
```

### Actual output

```
{
  foo,
  bar,
  foobar,
}:
{
...
}
```

**Comment by piegamesde** [comment]
This is very much intended behavior for diffability purposes, see https://piegames.de/dumps/leading-commas/#the-issue for a more detailed explanation.

`...` is not followed by a comma because neither does it need one nor does the Nix syntax allow it in the first place.
