### ISSUE TITLE
Help setup with nixld and Neovim

### ISSUE THREAD

**Issue by minizilla** [NixOS/nixfmt#214]
### Description

I'm using Neovim with the following setup

```lua
local nvim_lsp = require("lspconfig")
nvim_lsp.nixd.setup({
   cmd = { "nixd" },
   settings = {
      nixd = {
         formatting = {
            command = { "nixfmt" },
         },
      },
   },
})
```
When try to format the nix file, nothing happened, no formatting, check with `nixfmt -c flake.nix` also report `flake.nix: not formatted`.

Previously I'm using `nixpkgs-fmt`, the formatter is worked well.
Can you help me how to setup **nixfmt** with **nixld** and **Neovim**?

**Comment by infinisil** [comment]
Can you make sure that you installed a recent version of nixfmt? Notably it's `pkgs.nixfmt-rfc-style` in Nixpkgs.

**Comment by minizilla** [comment]
You right @infinisil , using `pkgs.nixfmt-rfc-style` solve the issue. Thanks.
