### ISSUE TITLE
empty line is not formatted

### ISSUE THREAD

**Issue by linsui** [NixOS/nixfmt#226]
### Description

When there is empty lines the output is different.

### Small example input

```nix
{
  adcasdcasd =

    "ascarvefdvadfv";
}
```

### Expected output

```nix
{ adcasdcasd = "ascarvefdvadfv"; }
```

### Actual output

```nix
{
  adcasdcasd =

    "ascarvefdvadfv";
}
```

**Comment by infinisil** [comment]
This is working as expected [according to the standard](https://github.com/NixOS/nixfmt/blob/e819b2d0f9173f0c73d2e1fb4bc5155362046653/standard.md?plain=1#L68C77-L68C113):

> Single empty lines must be preserved, and consecutive empty lines must be collapsed into a single empty line.
>   This allows the formatter to expand or compact multi-line expressions, while still allowing grouping of code.

**Comment by linsui** [comment]
OK, thanks!
