### ISSUE TITLE
Version is inconsistent with what nixpkgs reports

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nixfmt#229]
When I look at nixpkgs/unstable right now, I see that on the current nixpkgs commit ([`52ec9ac3`](https://github.com/NixOS/nixpkgs/tree/52ec9ac3b12395ad677e8b62106f0b98c1f8569d)), the version of `nixfmt` is `2024-07-12`. 
![Screenshot 2024-07-31 at 12 05 03](https://github.com/user-attachments/assets/2054a93f-2a58-4ec7-95c6-3be56df106dd)

However, when I actually install that version, I still see 0.6.0:

```
$ nix run github:NixOS/nixpkgs/52ec9ac3b12395ad677e8b62106f0b98c1f8569d#nixfmt-rfc-style -- --version
nixfmt v0.6.0
```

This is not a big issue, but it would be nicer if the version reported binary was the same as the version of the nixpkgs package.

**Comment by infinisil** [comment]
We discussed this today in the formatting team meeting. To implement this, we could use [`embedFileIfExists ".version"`](https://hackage.haskell.org/package/file-embed-0.0.16.0/docs/Data-FileEmbed.html#v:embedFileIfExists) to get the version from if a `.version` file exists in the source. Then when building in Nixpkgs, use `echo -n ${rev} > .version` to create the file.

@dasJ is looking into implementing that.
