### ISSUE TITLE
Feature Request: --exclude parameter and builtin default excludes

### ISSUE THREAD

**Issue by phip1611** [NixOS/nixfmt#239]
Hi there!

Currently, `nixfmt .` fails in projects where I use `direnv` as it tries to reformat something in `.direnv`:

```console
nixfmt: ./.direnv/flake-inputs/pgildni8kbdhq7b28006b7px1qjf6jyp-source/nix: openTempFileWithDefaultPermissions: permission denied (Read-only file system)
```

A nice solution would be:
- automatic excludes (gitignore file? hardcoded list, such as `.direnv`)
- `-E/--exclude` parameter

Would be cool to see this in the future. Keep up the great work!

**Comment by infinisil** [comment]
This is a known issue, but we decided to defer file filtering to other tools: https://github.com/NixOS/nixfmt/issues/151#issuecomment-2008026386
