### ISSUE TITLE
rather simple decimal floats are converted to scientific / "E" notation

### ISSUE THREAD

**Issue by WilliButz** [NixOS/nixfmt#244]
### Description

Literal floats that I'd consider short and simple enough to represent them in decimal notation are reformatted to scientific / e notation.
I didn't find any specific reasoning about this behavior and I find it quite unexpected, therefore this issue.

### Small example input

```nix
{ a = 0.2; b = 0.068; c = 0.009; }
```

### Expected output

```nix
{
  a = 0.2;
  b = 0.068;
  c = 0.009;
}
```

### Actual output

```nix
{
  a = 0.2;
  b = 6.8e-2;
  c = 9.0e-3;
}
```

**Comment by infinisil** [comment]
Damn, I don't even think I knew that Nix supports scientific notation, nor that nixfmt rewrites floats in that way. Definitely should be fixed!
