### ISSUE TITLE
Having an empty multiline set as the last parameter in an application in a set puts it on an extra line

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixfmt#253]
That title should describe it… sorry for the length of it.

Given this input:
```nix
{
  test = app {
  };
}
```

I would expect the expression not to be reformatted at all. The current master version however returns:
```nix
{
  test =
    app
      {
      };
}
```

Interestingly enough, having a non-expanded second argument prevents this from happening, resulting in:
```nix
{
  test = app {
  } { };
}
```

It does however also happen if I start with two already-expanded attrsets as the parameters:
```nix
{
  test =
    app
      {
      }
      {
      };
}
```

**Comment by piegamesde** [comment]
That looks like a regression, could you maybe bisect it?

**Comment by dasJ** [comment]
Introduced by 23b4c1f51cd7ea2f32912b09f070a43afe63aefd. In the previous commit (aff0520720cf913523d6e3a45dd7df8a1b2516fa), we have the old contraction logic which causes the entire file to be put into a single line.
