### ISSUE TITLE
Add a flag for overriding the filename of files passed through stdin

### ISSUE THREAD

**Issue by pluiedev** [NixOS/nixfmt#263]
### Description

Tools that automatically format files (e.g. Neovim, Jujutsu with `jj fix`, etc.) often work by calling a formatter like Nixfmt by passing a file's contents to stdin and then getting the formatted result via stdout, which has the benefit that the caller would have complete control over the original file, instead of having the formatter potentially overwriting it.

However, a drawback is that when there is a formatting error, all context around the *filename* is lost, which could be frustrating when dozens of files are involved:
```console
$ jj fix
<stdin>:71:3:
   |
71 |   '';
   |   ^
unexpected '''
expecting expression
```

Some other formatters like `clang-format` allow the user to supply the actual filename via an CLI option (e.g. `--assume-filename`) while still accepting input via stdin, and I think it would be great if Nixfmt would have something similar.

**Comment by piegamesde** [comment]
Shouldn't it be the job of the tool calling Nixfmt to wrap the error with additional context containing the file name?

**Comment by pluiedev** [comment]
> Shouldn't it be the job of the tool calling Nixfmt to wrap the error with additional context containing the file name?

Then it would require the tool to parse Nixfmt's error output over stderr which is honestly unreasonable when it's supposed to be formatter-agnostic

**Comment by dasJ** [comment]
While it's very ugly, one thing that can be done is this: https://github.com/NixOS/nixpkgs/pull/300430/files#diff-d5f772f74ac67b1f8e91bcd69c1f660dc34ad7f2f59088a11d8a7f33dc88c306R111

**Comment by pluiedev** [comment]
It works TM
```console
$ echo "{a=3}" | nix run . -- --filename "hahaha.nix"
hahaha.nix:1:5:
  |
1 | {a=3}
  |     ^
unexpected '}'
expecting expression
```

PR soon
