### ISSUE TITLE
Weird line break in empty attrsets

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixfmt#265]
### Description

Found by @Atemu. Needs to be bisected, but I strongly suspect that this is a regression of #224

### Small example input

```nix
{
  foo = {
  };
}
```

### Expected output

no change, or

```nix
{
  foo = { };
}
```

### Actual output

```nix
{
  foo =
    {
    };
}
```

**Comment by dasJ** [comment]
Duplicate of #253 ?

**Comment by piegamesde** [comment]
Unclear, but likely. The other bug looks really similar, but all examples use function applications while this one is directly on an attrset, which is special cased and thus a different code path. So maybe keep this one open in case a fix for one doesn't also fix the other.

**Comment by piegamesde** [comment]
Duplicate of #253
