### ISSUE TITLE
Breaking == Vs. ||

### ISSUE THREAD

**Issue by rycee** [NixOS/nixfmt#72]
### Description

It seems `==` is preferred as a break point over the logic operators `||` and `&&`. I think it should be the opposite, at least I can't think of a situation where I'd like to break on `==` over `||`.

Perhaps when comparing two logical expressions? Like `(a || b) == (c && d)` but I think this is less common and you have to insert parentheses anyway.

### Small example input

```
let
  isReserved = n: n == "hmModules" || n == "lib" || n == "modules" || n == "ndModules" || n == "overlays";
in
  isReserved
```

### Expected output

```
let
  isReserved = n:
    n == "hmModules" || n == "lib" || n == "modules" || n == "ndModules"
    || n == "overlays";
in isReserved
```

### Actual output

```
let
  isReserved = n:
    n == "hmModules" || n == "lib" || n == "modules" || n == "ndModules" || n
    == "overlays";
in isReserved
```

**Comment by piegamesde** [comment]
This is fixed in #118, where operators are treated according to their binding precedence:

```nix
let
  isReserved =
    n:
    n == "hmModules"
    || n == "lib"
    || n == "modules"
    || n == "ndModules"
    || n == "overlays"
    ;
in
isReserved
```
