### ISSUE TITLE
Nixfmt does not persist file ownership

### ISSUE THREAD

**Issue by jnsaff** [NixOS/nixfmt#73]
### Description
When run on a file to be formatted in place nixfmt does not persist file ownership. When run as a user that is not the owner of the file but has permissions to edit the file the formatted file ownership will be changed to the user running nixfmt.

This can be easily worked around and is a remote edge case to begin with but I'm reporting it still for completeness sake.

Thank you for the great work from a fellow nixer from Tallinn!

**Comment by kirelagin** [comment]
Oh, yes, you are right, thanks for the report!

The reason here is that we do an atomic write by creating a new file and then `mv`ing it in place. I suspect it might be impossible to preserve 100% of permissions, but we should, at least, try.

**Comment by dasJ** [comment]
Not sure if linux lets you create a file for another user without `CAP_CHOWN` anyway :/

**Comment by infinisil** [comment]
Fixed with https://github.com/NixOS/nixfmt/pull/248
